[theme]
# Colores oscuros/rojos
base="dark"

# Color de texto principal (botones, enlaces, métricas)
primaryColor="#FF4B4B"

# Color de fondo principal (negro o gris oscuro)
backgroundColor="#11111f" 

# Color del fondo de las tarjetas o elementos (gris oscuro)
secondaryBackgroundColor="#212529" 

# Color de texto (blanco)
textColor="#FFFFFF" 

# Fuente por defecto
font="sans serif"

[global]
# Esta configuración asegura que las variables de entorno de color sean usadas.
# (Generalmente no es necesario cambiarla, pero es buena práctica)
# developmentMode = false